### ISSUE TITLE
用了一次后不知道为什么就用不了，已解决！用录播中复制的xml做测试导致的不可用

### ISSUE THREAD

**Issue by ANLzz** [renmu123/biliLive-tools#1]
用了一次后不知道为什么就用不了
[2023-11-26 20:04:08.558] [error] stderr 
ERROR
Invalid type-name "table".

[main.log](https://github.com/renmu123/biliLive-tools/files/13466639/main.log)
![image](https://github.com/renmu123/biliLive-tools/assets/25404361/a4bdb843-167c-4593-81e2-6e78974f63f1)

1，不支持blrec录制的xml,等DanmakuFactory更新或在项目上编译个
2，投稿视频封面自定义
3，之后支持压制高能进度条时候希望也能支持输出高能简介，醒目留言列表写入到TXT

**Comment by renmu123** [comment]
1. `C:\Users\lan12\AppData\Local\Programs\biliLive-tools\resources\app.asar.unpacked\resources\bin\DanmakuFactory.exe -i "D:\blrec\录播文件\27183290 - 雪糕cheese\blive_27183290_2023-11-25-200233.xml" -o "D:\blrec\录播文件\27183290 - 雪糕cheese\blive_27183290_2023-11-25-200233.ass" --ignore-warnings --resolution 1920x1080 --scrolltime 12 --fixtime 5 --density 0 --fontname "Microsoft YaHei" --fontsize 42 --opacity 204 --outline 0 --shadow 1 --displayarea 0.8 --scrollarea 0.8 --bold true --showusernames false --showmsgbox true --msgboxsize 265x580 --msgboxpos 0x380 --msgboxfontsize 26 --msgboxduration 0 --giftminprice 10 --giftmergetolerance 0 --blockmode null --statmode null` 你尝试的cmd中输入一下看看有什么报错，log里看不到报错，理论上danmufactory支持blrec，但是sc之类的金额会失真，之后会支持自动转换成录播姬的格式再进行转换。战鹰那个弹幕你等录制完成后再转码试一下，看上去是danmufactory有什么字段解析错误了。
2. 这个确实是我漏了，过两天就会加上~~我一直都是懒得加，不加应该会默认使用第一帧~~
3. 这个会做的，我之后还想做审核完自动评论置顶

**Comment by ANLzz** [comment]
现在有个问题是用不了，重装软件也没用
[main.log](https://github.com/renmu123/biliLive-tools/files/13466826/main.log)

![image](https://github.com/renmu123/biliLive-tools/assets/25404361/8e38e25c-6271-411a-972d-fb8d50809d14)

**Comment by renmu123** [comment]
> 现在有个问题是用不了，重装软件也没用 [main.log](https://github.com/renmu123/biliLive-tools/files/13466826/main.log)
> 
> ![image](https://private-user-images.githubusercontent.com/25404361/285652622-8e38e25c-6271-411a-972d-fb8d50809d14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDQzNzcsIm5iZiI6MTcwMTAwNDA3NywicGF0aCI6Ii8yNTQwNDM2MS8yODU2NTI2MjItOGUzOGUyNWMtNjI3MS00MTFhLTk3MmQtZmI4ZDUwODA5ZDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEzMDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNzI1YjU0YTcxNjI0OTgwNGY4ZjYwODg5OTE0NmEwYzBmYTE4MzVlMmVmOWZhNGRiNmFjM2Q3OTQ3MTdhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cBoEWuQYLKdcrs_NwOeEzVcTjFwmFUrSXaDgkQ0_HPM)

你把这个弹幕文件发一下

**Comment by ANLzz** [comment]
4，渲染中点 结束任务 希望能像ffmpeg ctrl+c一样 能看停止渲染之前的视频内容

**Comment by ANLzz** [comment]
> > 现在有个问题是用不了，重装软件也没用 [main.log](https://github.com/renmu123/biliLive-tools/files/13466826/main.log)
> > ![image](https://private-user-images.githubusercontent.com/25404361/285652622-8e38e25c-6271-411a-972d-fb8d50809d14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDQzNzcsIm5iZiI6MTcwMTAwNDA3NywicGF0aCI6Ii8yNTQwNDM2MS8yODU2NTI2MjItOGUzOGUyNWMtNjI3MS00MTFhLTk3MmQtZmI4ZDUwODA5ZDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEzMDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNzI1YjU0YTcxNjI0OTgwNGY4ZjYwODg5OTE0NmEwYzBmYTE4MzVlMmVmOWZhNGRiNmFjM2Q3OTQ3MTdhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cBoEWuQYLKdcrs_NwOeEzVcTjFwmFUrSXaDgkQ0_HPM)
> 
> 你把这个弹幕文件发一下
[录制-23141761-20231126-185907-405-航海回馈来喽~.zip](https://github.com/renmu123/biliLive-tools/files/13466850/-23141761-20231126-185907-405-.zip)

**Comment by renmu123** [comment]
> > 1. `C:\Users\lan12\AppData\Local\Programs\biliLive-tools\resources\app.asar.unpacked\resources\bin\DanmakuFactory.exe -i "D:\blrec\录播文件\27183290 - 雪糕cheese\blive_27183290_2023-11-25-200233.xml" -o "D:\blrec\录播文件\27183290 - 雪糕cheese\blive_27183290_2023-11-25-200233.ass" --ignore-warnings --resolution 1920x1080 --scrolltime 12 --fixtime 5 --density 0 --fontname "Microsoft YaHei" --fontsize 42 --opacity 204 --outline 0 --shadow 1 --displayarea 0.8 --scrollarea 0.8 --bold true --showusernames false --showmsgbox true --msgboxsize 265x580 --msgboxpos 0x380 --msgboxfontsize 26 --msgboxduration 0 --giftminprice 10 --giftmergetolerance 0 --blockmode null --statmode null`尝试你的cmd中输入一下看看有什么报错，log里看不到报错，理论上danmufactory支持blrec，但是sc之类的视觉效果会失真，之后会支持自动转换成录播姬的格式再进行转换。战完成鹰那个弹幕你等录制之后转码试一下，查看是danmufactory有什么字段解析错误了。
> 
> 1.卡在这里，这是xml文件， [xml-blive_27183290_2023-11-25-200233.zip](https://github.com/renmu123/biliLive-tools/files/13466813/xml-blive_27183290_2023-11-25-200233.zip)
> 
> PS C:\Users\lan12\AppData\Local\Programs\biliLive-tools\resources\app.asar.unpacked\resources\bin> ./DanmakuFactory.exe -i "1.xml" -o "1.ass" --ignore-warnings --resolution 1920x1080 --scrolltime 12 --fixtime 5 --density 0 --fontname "Microsoft YaHei" --fontsize 42 --opacity 204 --outline 0 --shadow 1 --displayarea 0.8 --scrollarea 0.8 --bold true --showusernames false --showmsgbox true --msgboxsize 265x580 --msgboxpos 0x380 --msgboxfontsize 26 --msgboxduration 0 --giftminprice 10 --giftmergetolerance 0 --blockmode null --statmode null
> 
> DanmakuFactory 1.70 CLI Release by hkm ([hkm@tikm.org](mailto:hkm@tikm.org)) https://github.com/hihkm/DanmakuFactory
> 
> Input file(s): Number|Template |TimeShift|FileName 1|xml | 0.000s|1.xml
> 
> Output file: Format|FileName ass|1.ass
> 
> Loading files... Loading file "1.xml"
> 
> File Loading Complete.. Danmaku Pool: 1289 blive_27183290_2023-11-25-200233.zip)
> 
> Sorting...
> 
> Writting file "1.ass"...

是由于“弹幕设置-礼物栏设置-礼物框持续时间”设置为了0秒，导致卡住了，如果你想关闭礼物框，可以尝试关闭“显示礼物框”选项，并把“礼物持续时间”不设置为0秒，下个版本如果设置了“礼物框持续时间”为0秒，进行弹幕转换时会关闭“显示礼物框”

**Comment by ANLzz** [comment]
> 是由于“弹幕设置-礼物栏设置-礼物框持续时间”设置为了0秒，导致卡住了，如果你想关闭礼物框，可以尝试关闭“显示礼物框”选项，并把“礼物持续时间”不设置为0秒，下个版本如果设置了“礼物框持续时间”为0秒，进行弹幕转换时会关闭“显示礼物框”

礼物框持续时间”设置为了0秒，我是根据这个设置的
![image](https://github.com/renmu123/biliLive-tools/assets/25404361/0b9560e2-249e-433f-bdf2-e41a28957b4e)

**Comment by renmu123** [comment]
> > 是由于“弹幕设置-礼物栏设置-礼物框持续时间”设置为了0秒，导致卡住了，如果你想关闭礼物框，可以尝试关闭“显示礼物框”选项，并把“礼物持续时间”不设置为0秒，下个版本如果设置了“礼物框持续时间”为0秒，进行弹幕转换时会关闭“显示礼物框”
> 
> 礼物框持续时间”设置为了0秒，我是根据这个设置的 ![image](https://private-user-images.githubusercontent.com/25404361/285654545-0b9560e2-249e-433f-bdf2-e41a28957b4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDYyMTYsIm5iZiI6MTcwMTAwNTkxNiwicGF0aCI6Ii8yNTQwNDM2MS8yODU2NTQ1NDUtMGI5NTYwZTItMjQ5ZS00MzNmLWJkZjItZTQxYTI4OTU3YjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEzMzgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YzdlNDI4MjVlNzEyZTM2Njg0YjljYjQ5NzZjYzM2ZjllNGUyNWE5ZGMzNWM1ZWZiNDljYTY2YjgyN2MzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YEkbjkyJQkrBI51vqArNPdc6XPub6U4BCK7G4ugrm8I)

我的印象中`danmufactory`1.7.0没有GUI，你用得是啥第三方的吗

**Comment by ANLzz** [comment]
> 我的印象中`danmufactory`1.7.0没有GUI，你用得是啥第三方的吗

https://www.bilibili.com/read/cv25613485/  DanmakuFactory的贡献者打包了一份 1.70 图形界面预览版

**Comment by ANLzz** [comment]
> 这个之后得测试一下，刚才试了一下相同配置转录播姬的弹幕是不会卡住的

DanmakuFactory项目已经支持blrec了，就是没更新打包出最新版本软件

**Comment by ANLzz** [comment]
5,DanmakuFactoryConfig多模板？ 
![image](https://github.com/renmu123/biliLive-tools/assets/25404361/61be3fb9-a878-4cdb-a33d-f4c5f10d1f97)

**Comment by renmu123** [comment]
> > 1. `战鹰那个弹幕你等录制完成后再转码试一下，看上去是danmufactory有什么字段解析错误了。
> 
> 奇怪，之前用录播没完成的flv，xml都能行。。。

”弹幕设置-画面设置-调试“这个选项里的东西先不要使用，有bug
然后删掉`C:\Users\lan12\AppData\Roaming\biliLive-tools\DanmakuFactoryConfig.json`配置文件，配置文件有污染导致报错了。用户名可能需要替换为你的

**Comment by renmu123** [comment]
预计本周上半周会发个版本修复以下问题

已知bug:
1. **“弹幕设置-画面设置-调试”选项无法使用，如果勾选过需要删除数据文件中的`DanmakuFactoryConfig.json`才可恢复**
2. blrec弹幕在“礼物框设置为”0秒后进行转换，会出现卡住的情况

需求
1. 上传视频支持封面
2. 弹幕文件支持预设
3. 修改ffmpeg中断信号

**Comment by ANLzz** [comment]
> 2. blrec弹幕在“礼物框设置为”0秒后进行转换，会出现卡住的情况

这个是DanmakuFactory的原因，我在Ubuntu按DanmakuFactory项目编译了最新版本就支持blrec了

**Comment by ANLzz** [comment]
这个问题关了，用录播中复制的xml做测试导致的不可用

**Comment by renmu123** [comment]
> 预计本周上半周会发个版本修复以下问题
> 
> 已知bug:
> 
> 1. **“弹幕设置-画面设置-调试”选项无法使用，如果勾选过需要删除数据文件中的`DanmakuFactoryConfig.json`才可恢复**
> 2. blrec弹幕在“礼物框设置为”0秒后进行转换，会出现卡住的情况
> 
> 需求
> 
> 1. 上传视频支持封面
> 2. 弹幕文件支持预设
> 3. 修改ffmpeg中断信号

0.3.1已增加相应功能，新版本卸载时会删除相关的用户数据，以防出现配置文件出错从而无法使用的情况。
0.4.0预计会增加blrec的webhook支持，以及重构任务相关部分代码，为支持webhook 的压制上传做准备
