### ISSUE TITLE
需求可修改视频分辨率 2k 改4k

### ISSUE THREAD

**Issue by q1518001822** [renmu123/biliLive-tools#10]
将2k 视频 重新编码渲染成4k 带弹幕  h264 afm硬件加速 支持

**Comment by q1518001822** [comment]
损失小也可以

**Comment by renmu123** [comment]
2k转4k有什么实际意义吗？你画质并不会变清晰，反而在压制的过程中会有损失

**Comment by q1518001822** [comment]
意义重大(🎖️¯^¯)ゞ

**Comment by renmu123** [comment]
下个版本支持

**Comment by q1518001822** [comment]
弄好高低冲个电感谢大佬

**Comment by ANLzz** [comment]
> 2k转4k有什么实际意义吗？你画质并不会变清晰，反而在压制的过程中会有损失

B站会把2k二压成1080，4K就不会变分辨率还能有更好视频码率上限

**Comment by renmu123** [comment]
https://github.com/renmu123/biliLive-tools/releases  0.10.0已发布
