### ISSUE TITLE
是否有可能自动识别视频文件名称为视频标题

### ISSUE THREAD

**Issue by Georgebillion** [renmu123/biliLive-tools#11]
本人使用的是blrec录制的，且是通过blrec设置好了我所需要的标题
现在想问一下作者，有无可能通过webhook所获取的文件名作为投稿的标题？我们这里有更高时间精度的要求，且因为设置的是分段，所以不知道是否能支持分P续传功能？

**Comment by renmu123** [comment]
blrec 的webhook目前好像有问题，文件名明明是`.mp4`结尾，webhook传递过来的参数确实`.flv`后缀

**Comment by Georgebillion** [comment]
看了一下，如果开转码，会直接报错，不清楚是为啥，然后剩下的一个问题已经解决了，我就直接closed了

**Comment by renmu123** [comment]
blrec开了转码之后，webhook传递过来的文件名不一致，导致失败。

这个版本还有两个可能会导致失败的原因，会在下个版本修复：
1. 电脑用户名中存在空格
2. 弹幕内容为空
