### ISSUE TITLE
1.0.0-alpha相关版本webhook功能在blrec报错

### ISSUE THREAD

**Issue by Georgebillion** [renmu123/biliLive-tools#15]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 已阅读文档，并查询过 issue

### 复现步骤

1.设置host为127.0.0.1
2.port设置为10086
3.blrec-webhook中设置成相关地址，并打开所有功能

### 预期行为

能自动处理稿件

### 实际行为

直接报错，无法自动化上传
![image](https://github.com/renmu123/biliLive-tools/assets/40432824/81e6d901-6c77-43b9-a778-13b72f5b2777)

### 分享log

[main.log](https://github.com/renmu123/biliLive-tools/files/15467817/main.log)

**Comment by renmu123** [comment]
这是一个bug，已确认

**Comment by Georgebillion** [comment]
> 这是一个bug，已确认

需要解决方案，我这个是给甲方服务的，现在已经被骂了好几圈了

**Comment by renmu123** [comment]
你可以自己编译1.0.0分支代码，或者在master分支自行修复
![图片](https://github.com/renmu123/biliLive-tools/assets/26896790/f93311ec-2976-41ca-a545-9b507df17a44)

https://github.com/renmu123/biliLive-tools/blob/348f02401cc30d30b31f9b0e9122b43d38dbc66c/packages/http/src/routes/webhook.ts#L225C78-L226C73

**Comment by Georgebillion** [comment]
client错误？

**Comment by renmu123** [comment]
> client错误？

你需要删除client

**Comment by Georgebillion** [comment]
> > client错误？
> 
> 你需要删除client

行吧，看来我需要clone一下代码去自行编译了，或者我交一个PR？

**Comment by renmu123** [comment]
> > > client错误？
> > 
> > 你需要删除client
> 
> 行吧，看来我需要clone一下代码去自行编译了，或者我交一个PR？
> 

1.0.0分支已经修复，但是由于是非正式分支，不能确保实现的其他功能没有bug。
你也可以fork修复之后，使用github action来进行构建

**Comment by renmu123** [comment]
fix in [1.0.0](https://github.com/renmu123/biliLive-tools/releases/tag/1.0.0)
