### ISSUE TITLE
多用户同步上传出现异常

### ISSUE THREAD

**Issue by Georgebillion** [renmu123/biliLive-tools#16]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 已阅读文档，并查询过 issue

### 复现步骤

1.设置多个webhook自动化
2.开始录制监听
3.开始上传

### 预期行为

多个webhook之间应该不会互相影响并上传到指定账户

### 实际行为

多个webhook会只上传到所应用的账户内，哪怕这个账户不是我需要上传的

### 分享log

[main.log](https://github.com/user-attachments/files/16015080/main.log)

**Comment by renmu123** [comment]
你是两个账户同时执行上传的吗？
我看一下代码是可能有这种bug产生的，我会在下个版本尝试修复，在此之前请不要同时使用多个账户在相同时段进行上传操作

**Comment by Georgebillion** [comment]
> 你是两个账户同时执行上传的吗？ 我看一下代码是可能有这种bug产生的，我会在下个版本尝试修复，在此之前请不要同时使用多个账户在相同时段进行上传操作

对的，而且有的时候会抽风，麻烦了

**Comment by xuqingxin001** [comment]
> 你是两个账户同时执行上传的吗？ 我看一下代码是可能有这种bug产生的，我会在下个版本尝试修复，在此之前请不要同时使用多个账户在相同时段进行上传操作

这情况我在不是webhook的时候也遇到过 切换账号以后还是会上传上一个账号 只能退出软件才能解决

**Comment by renmu123** [comment]
> > 你是两个账户同时执行上传的吗？ 我看一下代码是可能有这种bug产生的，我会在下个版本尝试修复，在此之前请不要同时使用多个账户在相同时段进行上传操作
> 
> 这情况我在不是webhook的时候也遇到过 切换账号以后还是会上传上一个账号 只能退出软件才能解决

涉及多账户的情况都会有可能出现这个问题

**Comment by renmu123** [comment]
https://github.com/renmu123/biliLive-tools/actions/runs/9715791564

应当是修好了，我简单测试过，你可以测试使用一下看看是否还有问题

**Comment by Georgebillion** [comment]
> https://github.com/renmu123/biliLive-tools/actions/runs/9715791564
> 
> 应当是修好了，我简单测试过，你可以测试使用一下看看是否还有问题

好的，我先测试一下
有问题我在这里继续交comment

**Comment by Georgebillion** [comment]
> https://github.com/renmu123/biliLive-tools/actions/runs/9715791564
> 
> 应当是修好了，我简单测试过，你可以测试使用一下看看是否还有问题

这个版本暂时性没出大问题，我先closed了
