### ISSUE TITLE
webhook自动化上传时会出现封面混乱情况

### ISSUE THREAD

**Issue by Georgebillion** [renmu123/biliLive-tools#17]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 已阅读文档，并查询过 issue

### 复现步骤

1.打开webhook自动化，并在blrec端做好封面保存设置
2.开始监听录播
3.开始上传录播并加上封面

### 预期行为

webhook能处理对应的封面

### 实际行为

webhook将一个不属于该视频的封面作为了稿件封面，且因为B站二次修改需要封面大于960*540，但实际封面不能满足这一要求，导致需要二次覆盖

### 分享log

[main.log](https://github.com/user-attachments/files/16028454/main.log)

**Comment by Georgebillion** [comment]
![image](https://github.com/renmu123/biliLive-tools/assets/40432824/c45eb2c0-7562-4292-95cd-e0bb780861c3)
补充相关图片，图片中第二个是错误的封面，而第一个是正确的，第二个是自动化录播所处理的，第一个是本人人工覆盖上传的

**Comment by renmu123** [comment]
你是不是开了断播续传以及使用直播间封面功能，我刚才确认了这两个功能同时使用会导致“使用直播间封面”功能失效，会在下个版本修复

**Comment by Georgebillion** [comment]
> 你是不是开了断播续传以及使用直播间封面功能，我刚才确认了这两个功能同时使用会导致“使用直播间封面”功能失效，会在下个版本修复

对的

**Comment by renmu123** [comment]
断播续传是一个很重要的参数，webhook中很大一部分代码都为是这个功能服务的，它的上传相关代码和不开启的情况下是完全独立的

**Comment by renmu123** [comment]
fix in [1.2.0](https://github.com/renmu123/biliLive-tools/releases/tag/1.2.0)
