### ISSUE TITLE
user字段在标题内无法应用

### ISSUE THREAD

**Issue by Georgebillion** [renmu123/biliLive-tools#18]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 已阅读文档，并查询过 issue

### 复现步骤

1.在标题内加入user字段
2.监听录播
3.webhook回传并上传录播

### 预期行为

user字段应自动识别主播名并应用

### 实际行为

user字段无效，标题内无主播名

### 分享log

[main.log](https://github.com/user-attachments/files/16041171/main.log)

**Comment by Georgebillion** [comment]
![image](https://github.com/renmu123/biliLive-tools/assets/40432824/8b15a569-de0e-42ce-b550-17191a4db8d1)
这是人工覆盖的记录，最上面的是自动上传的，下面是人工修改标题的，使用版本是之前作者给的1.2.0版本，修改了 #16 #17 的bug的版本 @renmu123

**Comment by Georgebillion** [comment]
![image](https://github.com/renmu123/biliLive-tools/assets/40432824/6f35e4a7-b978-4efc-9c7b-df01ac8be2bc)
附加上图片，本人已在设置内应用user字段

**Comment by renmu123** [comment]
看了一下log没发现啥问题，测试了一下也没啥问题，由于log里没有录播开始时的webhook请求和设置内容，我怀疑你是在录播开始后才在设置中修改的标题配置，标题会在一收到录制开始的webhook时就被确定下来了

**Comment by Georgebillion** [comment]
> 看了一下log没发现啥问题，测试了一下也没啥问题，由于log里没有录播开始时的webhook请求和设置内容，我怀疑你是在录播开始后才在设置中修改的标题配置，标题会在一收到录制开始的webhook时就被确定下来了

意思就是最好开播前设置好对吗？如果是这样的话，那我这边清楚了，顺带还是想催更一下自动切片这个功能

**Comment by renmu123** [comment]
> > 看了一下log没发现啥问题，测试了一下也没啥问题，由于log里没有录播开始时的webhook请求和设置内容，我怀疑你是在录播开始后才在设置中修改的标题配置，标题会在一收到录制开始的webhook时就被确定下来了
> 
> 意思就是最好开播前设置好对吗？如果是这样的话，那我这边清楚了，顺带还是想催更一下自动切片这个功能

要等1.3.0了，还有细节需要打磨，也不能叫自动切片，顶多是找到弹幕较多的时间点并支持导出到losslesscut进行额外处理，以及支持导入losscutless的时间戳进行渲染弹幕，避免渲染全部视频
