### ISSUE TITLE
请求获得视频标题支持格式的进一步解释

### ISSUE THREAD

**Issue by sdbztpy** [renmu123/biliLive-tools#21]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 查看是否有人已经提出过类似的功能请求

### 描述

请问视频标题支持的语法有哪些，因为我看到有类似{{now}}{{yyyy}}这样的表述，就以为和录播姬的基本一样，结果用了{{ "now" | time_zone: "Asia/Shanghai" | format_date: "yyMMdd" }}这样的想输出六位数的当天日期比如240814但是没有识别到。请问如果我想输出这样的日期的话，应该如何填写？是不是只能使用在软件GUI中显示的占位符？如果有更灵活的选择的话，能否在软件中或者B站教程视频给出更详细的说明？

**Comment by renmu123** [comment]
目前不支持，但我会考虑支持一个js模板引擎
