### ISSUE TITLE
未来会支持程序多开吗

### ISSUE THREAD

**Issue by xuqingxin001** [renmu123/biliLive-tools#22]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 查看是否有人已经提出过类似的功能请求

### 描述

现在只能运行一个程序 我昨天又遇到需要两个账号同时上传录播的情况，一个程序上传中 切换账号不是会失败吗？

**Comment by renmu123** [comment]
切换账号cookie混乱的bug应该在1.2.0已经修复了，我简单测试了一下也没问题，1.4.0版本又出现类似问题了吗？

**Comment by xuqingxin001** [comment]
> 切换账号cookie混乱的bug应该在1.2.0已经修复了，我简单测试了一下也没问题，1.4.0版本又出现类似问题了吗？

现在允许上传过程中切换账号了？ 就是我正上传一个录播 我切换另一个账号传另一个录播

**Comment by renmu123** [comment]
理论是一直支持的，只是在1.2.0版本之前有bug无法使用
