### ISSUE TITLE
自动上传当天录播能自动分p上传吗而不是单独多个稿件 要自动的 不是手动续传

### ISSUE THREAD

**Issue by q1518001822** [renmu123/biliLive-tools#24]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 查看是否有人已经提出过类似的功能请求

### 描述

自动上传当天录播能自动分p上传吗而不是单独多个稿件 要自动的 不是手动续传

**Comment by renmu123** [comment]
blrec和录播姬可以使用webhook并打开“断播续传”选项，其余工具需要自行调用webhook来实现
