### ISSUE TITLE
希望可以增加弹幕显示区域设置

### ISSUE THREAD

**Issue by TimingBule** [renmu123/biliLive-tools#25]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [x] 查看是否有人已经提出过类似的功能请求

### 描述

有时候弹幕太密集，只想限制上四分之一区域，不过目前来看最多就显示上半屏区域，可以调小字体减少区域，如果能增加手动设置就非常感谢

**Comment by renmu123** [comment]
![图片](https://github.com/user-attachments/assets/062b0969-0bdf-47ac-a483-285e599e798e)

**Comment by TimingBule** [comment]
找到了，非常感谢，原来在这里😂
