### ISSUE TITLE
转换弹幕用屏蔽词 屏蔽红包屏蔽不了

### ISSUE THREAD

**Issue by xuqingxin001** [renmu123/biliLive-tools#31]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 已阅读文档，并查询过 issue

### 复现步骤

![QQ20241002-234344](https://github.com/user-attachments/assets/328e65d3-7006-4b81-8e43-6aa909de3bb7)
设置界面
![QQ20241002-234420](https://github.com/user-attachments/assets/cdd4c465-b18f-4c18-bfb8-05ed9e16bd0e)
原文件
![QQ20241002-234510](https://github.com/user-attachments/assets/94ae1508-bad9-45b7-9727-b6796e860528)
转换后
log没有生成

这是弹幕文件
[录制-22697162-20241002-195838-381-psplive五周年文艺汇演！.zip](https://github.com/user-attachments/files/17232489/-22697162-20241002-195838-381-psplive.zip)

### 预期行为

![QQ20241002-234807](https://github.com/user-attachments/assets/2b0423b5-74e9-4e95-af2d-836ef7d6bd71)

### 实际行为

![QQ20241002-234510](https://github.com/user-attachments/assets/ddc52609-b2da-4d2f-8173-d7b699832c42)

**Comment by xuqingxin001** [comment]
我测试了下 1.3以前的都可以使用红包屏蔽词，1.3开始就无法去掉了

**Comment by renmu123** [comment]
![image](https://github.com/user-attachments/assets/187196ed-841f-4998-ba16-f7c061afb085)

comment其实是danmakuctory的注释弹幕，实际并不会参与渲染。  
1.3.0版本之前是由本软件来进行过滤，1.4.0版本之后为了性能修改为在danmakufactory进行过滤。  
你是否有对渲染的ass做什么分析的操作，底层有个是否展示注释弹幕的开关，我可以加上

**Comment by xuqingxin001** [comment]
> ![image](https://private-user-images.githubusercontent.com/26896790/373549741-187196ed-841f-4998-ba16-f7c061afb085.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMTYxNDEsIm5iZiI6MTcyODExNTg0MSwicGF0aCI6Ii8yNjg5Njc5MC8zNzM1NDk3NDEtMTg3MTk2ZWQtODQxZi00OTk4LWJhMTYtZjdjMDYxYWZiMDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA4MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMTViZmQ0MTA1MTZlODJkOGJhNmIxZjAzNTY1ZGVkZDVlYmEzZjE0NmM0MDFlYzY4Y2E1ZGQxZmMyODZjOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-Q9d7CopQW-UAaCDkNoBk8_0JG24xIau_hFV1I0d4AY)
> 
> comment其实是danmakuctory的注释弹幕，实际并不会参与渲染。 1.3.0版本之前是由本软件来进行过滤，1.4.0版本之后为了性能修改为在danmakufactory进行过滤。 你是否有对渲染的ass做什么分析的操作，底层有个是否展示注释弹幕的开关，我可以加上

我是选好设置里的参数直接转换的没有做分析操作

**Comment by renmu123** [comment]
实际渲染是不会有这个弹幕的，我没有将这个参数暴露出来~~忘记做这个参数了~~，下个版本加上

**Comment by renmu123** [comment]
这个参数的danmakufactory实现，有点问题，只支持部分冲突的弹幕屏蔽，并不支持屏蔽词及按类型屏蔽的弹幕

**Comment by renmu123** [comment]
1.5.2已发布
