### ISSUE TITLE
报错 READ ECONNRESET

### ISSUE THREAD

**Issue by Georgebillion** [renmu123/biliLive-tools#32]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 已阅读文档，并查询过 issue

### 复现步骤

1.打开webhook
2.录制软件开始录制
3.到点后开始自动化上传
4.完成

### 预期行为

无错误提示

### 实际行为

报错上传失败和read ECONNRESET

**Comment by renmu123** [comment]
本质上是B站上传出错了，而且这个错误没有被重试，下个版本会修复，如果下个版本还出现，建议拉大错误重试次数

**Comment by Georgebillion** [comment]
> 本质上是B站上传出错了，而且这个错误没有被重试，下个版本会修复，如果下个版本还出现，建议拉大错误重试次数

主要用的是您之前给的那个测试版，并不清楚那个版本是否已经修复了相关问题？

**Comment by renmu123** [comment]
> > 本质上是B站上传出错了，而且这个错误没有被重试，下个版本会修复，如果下个版本还出现，建议拉大错误重试次数
> 
> 主要用的是您之前给的那个测试版，并不清楚那个版本是否已经修复了相关问题？

那个版本还没有，最新版本这两天就会发出来了

**Comment by renmu123** [comment]
1.5.2已发布
