### ISSUE TITLE
现在合集功能对分P视频开放了

### ISSUE THREAD

**Issue by sdbztpy** [renmu123/biliLive-tools#33]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 查看是否有人已经提出过类似的功能请求

### 描述

随着B站电磁力改版，合集功能对分P视频开放了，可以考虑更改上传设定中的相关描述。

**Comment by renmu123** [comment]
哪里有相关说明吗？我好像并没有找到

**Comment by sdbztpy** [comment]
并没有相关说明，可能还在灰度测试阶段，我也是电磁力改版之后尝试了一下才发现的，这样的话大概暂时不着急改动吧，抱歉

**Comment by renmu123** [comment]
确认现在web可以加入分p，分p也可以加入合集了，我会修改相关逻辑

**Comment by sdbztpy** [comment]
看来是测试结束对所有人开放了，感谢！

**Comment by renmu123** [comment]
[1.5.3](https://github.com/renmu123/biliLive-tools/releases/tag/1.5.3) 已支持
