### ISSUE TITLE
增加GPU选项

### ISSUE THREAD

**Issue by wu15995944558** [renmu123/biliLive-tools#34]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 查看是否有人已经提出过类似的功能请求

### 描述

是不是可以增加个同时使用CPU GPU或者使用其中一项w我这个GPU没啥动静了 CPU猛猛干
![c433f42ff5028641466e4039e8531b99](https://github.com/user-attachments/assets/d367d287-4ca2-4172-b190-3d48460819cc)

**Comment by renmu123** [comment]
![图片](https://github.com/user-attachments/assets/7a27a8a9-4c7a-44c9-8d6c-59110ee5aec1)

需要自行根据硬件选择不同的编码器
