### ISSUE TITLE
切片功能疑问

### ISSUE THREAD

**Issue by xuqingxin001** [renmu123/biliLive-tools#35]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 查看是否有人已经提出过类似的功能请求

### 描述

切片功能必须加载弹幕文件才能切吗？我只需要切一段 不需要弹幕 工具提示我必须加载弹幕才能导出切片

**Comment by renmu123** [comment]
下版本会支持

**Comment by xuqingxin001** [comment]
> 下版本会支持

增加可选选项吗？

**Comment by renmu123** [comment]
无论是否有弹幕都可以进行分割

**Comment by xuqingxin001** [comment]
> 无论是否有弹幕都可以进行分割

好的 输入框的右键功能能实现吗 目前只能靠Ctrl+C/V复制粘贴标题和简介

**Comment by renmu123** [comment]
> > 无论是否有弹幕都可以进行分割
> 
> 好的 输入框的右键功能能实现吗 目前只能靠Ctrl+C/V复制粘贴标题和简介

也会在下个版本支持（下个大版本已经拖了几个月了，预计会在下周发布

**Comment by renmu123** [comment]
[1.6.0](https://github.com/renmu123/biliLive-tools/releases/tag/1.6.0) 已更新
