### ISSUE TITLE
切片保存位置问题

### ISSUE THREAD

**Issue by xuqingxin001** [renmu123/biliLive-tools#36]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 已阅读文档，并查询过 issue

### 复现步骤

![QQ截图20241113214708](https://github.com/user-attachments/assets/88d6ecd7-6e12-4516-8b31-0882552d04e0)
导出到录播所在文件夹了
![QQ截图20241113214743](https://github.com/user-attachments/assets/eb45543b-6e78-4c48-819f-573f29acdd6a)

### 预期行为

![QQ截图20241113214936](https://github.com/user-attachments/assets/ba23ccd5-137f-4765-99f0-3c8727e8c2b5)
应该导出到这

### 实际行为
![QQ截图20241113214936](https://github.com/user-attachments/assets/c7c42b1b-7e0f-40fe-beb5-1724b903d754)
本来应该导出到这

![QQ截图20241113214743](https://github.com/user-attachments/assets/3eb540cb-d091-4521-a80a-373a4d281c7f)
却导出到录播所在文件夹

### 分享log

[main.log](https://github.com/user-attachments/files/17733558/main.log)

**Comment by renmu123** [comment]
![图片](https://github.com/user-attachments/assets/016eeffc-3383-453d-9b8f-605d30880a26)
这里不是选择了`保存到视频文件夹`吗
