### ISSUE TITLE
使用转码功能压制视频时分辨率设置失效

### ISSUE THREAD

**Issue by sdbztpy** [renmu123/biliLive-tools#37]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 已阅读文档，并查询过 issue

### 复现步骤

为了产生无弹幕的伪4K视频，尝试用了转码功能调用之前带弹幕压制的时候写的压制预设配置，然后发现压制出的视频分辨率选项无效了，经查阅logs发现在用转码功能处理视频时，会抛弃-vf后面的全部参数，导致scale设置被连带清除，推测为bug出现原因。
目前可以在写压制预设配置的时候在额外输出参数里写上-s 2880x1620来解决，但是感觉这应该算bug，希望在将来的版本优化逻辑。

### 预期行为

转码功能调用预设配置压制时分辨率配置生效

### 实际行为

转码功能调用预设配置压制时分辨率配置无效

**Comment by renmu123** [comment]
确实是bug,将在之后版本修复

**Comment by renmu123** [comment]
closed  in https://github.com/renmu123/biliLive-tools/commit/b6dd544c773b3083e744f26920eb781c5848575f
