### ISSUE TITLE
硬编码时间参数到视频中时，需要调节字体/描边/阴影/显示格式等细节。

### ISSUE THREAD

**Issue by sdbztpy** [renmu123/biliLive-tools#38]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 查看是否有人已经提出过类似的功能请求

### 描述

尝试了1.6.0版本下的新功能，硬编码时间参数到视频中，发现默认的可调节字号/颜色选项不足以提供足够的辨识度，并且字体不能更改以与整体弹幕字体风格统一。
希望能够调整字体和描边的细节，支持自定义或自动套用弹幕字体。
希望可以设定时间戳的内容，选定展示范围，如隐藏日期仅显示时间等。

**Comment by renmu123** [comment]
字体展示和内容应该会增加相关选项，~~也许还能用来当水印~~

更多的样式控制不会增加选项，但可能会支持ffmpeg的自定义参数，因为ffmpeg支持的太多了，具体支持什么就得自己翻文档了

**Comment by sdbztpy** [comment]
感谢！filter_complex里的东西确实太杂了

**Comment by renmu123** [comment]
close in https://github.com/renmu123/biliLive-tools/commit/58df5dc1cf0ba07c70c80376233c36b0a2e35f8c

下个版本支持
