### ISSUE TITLE
现在已经有了断播续传功能了,想问下能不能加一个断播自动合并的功能

### ISSUE THREAD

**Issue by 12131adasda** [renmu123/biliLive-tools#40]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 查看是否有人已经提出过类似的功能请求

### 描述

如题,有时候会因为网络或者各种原因导致录制的一场直播终端变成两个文件,看到现在的程序里支持了自动将两个文件上传到一个投稿的操作.我就想能不能继续优化下,增加一个自动将两个视频压制成一个的选项,这样可能录播上传后能更方便看一点?

**Comment by renmu123** [comment]
合并文件会涉及很多问题，尤其是存在弹幕的，在合并的过程中涉及多个时间，时间可能又有偏差，导致弹幕的偏差越来越大。而且视频上传出错的概率也会变大。

目前web支持分p以及合集已经支持分p之后，我觉得这个需求的意义不是特别大

**Comment by 12131adasda** [comment]
明白了
