### ISSUE TITLE
[存疑] 首次登录账号无限弹出登录成功对话框

### ISSUE THREAD

**Issue by li7355608** [renmu123/biliLive-tools#43]
### 我已尝试以下操作

- [X] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [X] 已阅读文档，并查询过 issue

### 复现步骤

运行环境： win10
版本：1.6.1发行版
下载安装1.6.1版本，进入账号管理扫码登录账号，手机确认并成功登录账号

### 预期行为

登录成功弹窗只出现一次，不应重复出现

### 实际行为

登录成功弹窗重复出现，且退出账号后仍持续弹窗。在退出账号后关闭程序，重新登录恢复正常。可复现性存疑。

**Comment by renmu123** [comment]
你指得是右上角“登录成功”提示吗？代码看起来没啥bug，先加个关闭弹框后停止轮询吧（理论会有取消操作）

**Comment by li7355608** [comment]
> 你指得是右上角“登录成功”提示吗？代码看起来没啥bug，先加个关闭弹框后停止轮询吧（理论会有取消操作）

对，就是这个提示弹窗。不过由于关闭程序后再次登陆就没有触发这个问题，无法debug获取日志，具体原因存疑

**Comment by renmu123** [comment]
fix in https://github.com/renmu123/biliLive-tools/commit/a5aff9f81cd300dbefab0c861b9fa0a011e9e1e8
