### ISSUE TITLE
视频简介回车会直接变成\n 没有换行

### ISSUE THREAD

**Issue by 1753449579** [renmu123/biliLive-tools#5]
视频简介回车，上传后会变成\n 没有换行

![b1855e28b4668e8457f5b72567b8a038](https://github.com/renmu123/biliLive-tools/assets/90882660/ea9cefdc-6962-442c-aa91-103451476e79)
![c0b235770d7a19f64d5f9ef8d56ee4eb](https://github.com/renmu123/biliLive-tools/assets/90882660/600441bb-4a67-46dc-a2c0-67538b5aac60)

**Comment by renmu123** [comment]
使用的是biliup的命令行上传，\n会被转义掉，暂时没有办法解决。
下个版本开始会尝试替换掉biliup，届时会支持换行以及@等功能
