### ISSUE TITLE
blrec的webhook

### ISSUE THREAD

**Issue by 1753449579** [renmu123/biliLive-tools#6]
在VideoFileCompletedEvent后处理 是
![{E5CD20C1-D78E-4263-8A3D-005810AF5F40}](https://github.com/renmu123/biliLive-tools/assets/90882660/cdcd21e3-2664-40e6-afad-ba0233430ec5)
“视频后处理完成”这个吗

**Comment by renmu123** [comment]
不是，blrec支持视频录制完成后执行某些操作，比如转编码或压制弹幕等操作。
但是这个软件是不支持这个hook，也即在视频录制完成后就会被处理。

**Comment by 1753449579** [comment]
那软件会直接上传m4s文件吗

**Comment by 1753449579** [comment]
自动上传的是m4s格式的，怎么转码

**Comment by renmu123** [comment]
我记得blrec也是flv吧，具体我要测试一下

**Comment by 1753449579** [comment]
现在有个新的HLS的录制，录下来是m4s后缀的

**Comment by renmu123** [comment]
是不是开了原始模式录制

**Comment by 1753449579** [comment]
我用的是blrecv2.0.0-beta.3，没有录制模式的选项了
![image](https://github.com/renmu123/biliLive-tools/assets/90882660/b425a635-48c2-46b0-b6b5-52d181445151)

**Comment by Georgebillion** [comment]
> 我用的是blrecv2.0.0-beta.3，没有录制模式的选项了 ![image](https://private-user-images.githubusercontent.com/90882660/296808902-b425a635-48c2-46b0-b6b5-52d181445151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTI5MDksIm5iZiI6MTcwOTg5MjYwOSwicGF0aCI6Ii85MDg4MjY2MC8yOTY4MDg5MDItYjQyNWE2MzUtNDhjMi00NmIwLWI2YjUtNTJkMTgxNDQ1MTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDEwMTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMjJiNTY1ZWUwMGExNDkwMzNjZDkwOGJhMDgwYWFhZGY2ZDhkNWY2ZDFlNWI3MGU1NGQ4YjBiMDEzZGFlNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zqTl1rY4L9sbSmdfjT5BfkB_sf6Ci-iVKgVWpm284Ws)

是否你有无开转码？无转码现在输出确实是M4S，但可以转码压制成MP4

**Comment by 1753449579** [comment]
> > 我用的是blrecv2.0.0-beta.3，没有录制模式的选项了 ![image](https://private-user-images.githubusercontent.com/90882660/296808902-b425a635-48c2-46b0-b6b5-52d181445151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTI5MDksIm5iZiI6MTcwOTg5MjYwOSwicGF0aCI6Ii85MDg4MjY2MC8yOTY4MDg5MDItYjQyNWE2MzUtNDhjMi00NmIwLWI2YjUtNTJkMTgxNDQ1MTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDEwMTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMjJiNTY1ZWUwMGExNDkwMzNjZDkwOGJhMDgwYWFhZGY2ZDhkNWY2ZDFlNWI3MGU1NGQ4YjBiMDEzZGFlNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zqTl1rY4L9sbSmdfjT5BfkB_sf6Ci-iVKgVWpm284Ws)
> 
> 是否你有无开转码？无转码现在输出确实是M4S，但可以转码压制成MP4

解决了，现在B站又能用FLV流了

**Comment by Georgebillion** [comment]
> 我记得blrec也是flv吧，具体我要测试一下

现在B站大部分是HLS流了，且FLV流必二压，能麻烦作者适配一下M4S或者MP4吗？

**Comment by renmu123** [comment]
> > 我记得blrec也是flv吧，具体我要测试一下
> 
> 现在B站大部分是HLS流了，且FLV流必二压，能麻烦作者适配一下M4S或者MP4吗？

我试了一下m4s是支持的，如果设置为转换成mp4格式会导致错误
