### ISSUE TITLE
biliLive-tools投稿后修改不了视频简介，网页版投稿的视频则能正常修改简介

### ISSUE THREAD

**Issue by ANLzz** [renmu123/biliLive-tools#8]
biliLive-tools投稿后修改不了视频简介，网页版投稿的视频则能正常修改简介。。
另外催催高能条。。。
[录屏.zip](https://github.com/renmu123/biliLive-tools/files/14041630/default.zip)

**Comment by renmu123** [comment]
因为压根没有编辑功能，有的只是续传。我还在考虑要不要做完整的上传编辑功能，搞起来还挺复杂的，何况也不是这个项目的重点
